name: CI

on:
  push:
    branches:
      - master  # Run the workflow when code is pushed to 'master' branch

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up environment
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt

      - name: Run  API
        run: |
          python mock_api.py &  # Run API in background
          sleep 5  # Give it time to start up
          
      - name: Run unit tests
        run: |
          python -m unittest discover  # Run unit tests
